- src/controllers/documents.js
- test/controllers/documents.js
WATER-1833
Changes the response from `/crm/{documentId}/users` so that the user
roles are grouped into a single user object.
> Feat: Updates grouping in '/crm/{documentId}/users'

- src/controllers/entities.js
- test/controllers/entities.js
WATER-1833
Changes the logic for the entity companies response so that it returns a
404 if the entity does not exist, but a 200 if the entity is not
associated with any companies.
> Fix: Entity companies returns 200 for no companies

- src/v2/connectors/repository/queries/document-roles.js
- src/v2/modules/documents/lib/mappers.js
- test/v2/modules/documents/lib/mappers.js
Previously, the company ID was set during import of billing roles on a document.
This is no longer the case, so the company ID is now null.
This PR fixes an issue where this was stopping billing roles from being retrieved in the v2 documents API.
> Fixes an issue where billing roles were not retrieved for documents

- .codeclimate.json
- src/lib/camel-case-keys.js
- src/v2/connectors/repository/ContactsRepository.js
- src/v2/connectors/repository/DocumentRolesRepository.js
- src/v2/connectors/repository/DocumentsRepository.js
- src/v2/connectors/repository/Repository.js
- src/v2/connectors/repository/index.js
- src/v2/connectors/repository/queries/contacts.js
- src/v2/modules/contacts/controller.js
- src/v2/modules/contacts/routes.js
- src/v2/modules/documents/controller.js
- src/v2/modules/documents/lib/mappers.js
- src/v2/routes.js
- test/lib/camel-case-keys.js
- test/v2/connectors/repository/ContactsRepository.js
- test/v2/modules/contacts/controller.js
- test/v2/modules/documents/lib/mappers.js
WATER-2445
Adds endpoints to get a single contact from the API or alternatively get
many contacts by passing a comma separated list of ids to the API.
> Feat: Get contacts from the v2 crm

- src/lib/CRM.js
Due to recent changes standardising the creation of the Postgres pool, query data is now accessed in { rows } rather than { data } as was the case with the old function.
> Fix issue with colleagues endpoint (breaks share access flow)

- migrations/20200411131657-add-is-test-column.js
- migrations/sqls/20200411131657-add-is-test-column-down.sql
- migrations/sqls/20200411131657-add-is-test-column-up.sql
- src/v2/connectors/repository/companies.js
- src/v2/connectors/repository/index.js
- src/v2/lib/company-types.js
- src/v2/modules/companies/controller.js
- src/v2/modules/companies/routes.js
- src/v2/routes.js
- src/v2/services/companies.js
- test/v2/connectors/repository/companies.js
- test/v2/modules/companies/controller.js
- test/v2/modules/companies/routes.js
- test/v2/services/companies.js
WATER-2631
Adds endpoints to allow a companies to be saved and to be retrieved.
Adds the is_test flag to all the database tables that will have test
data written to for acceptance testing
> Feat: Create and retrieve company endpoints

- src/v2/connectors/bookshelf/CompanyContact.js
- src/v2/connectors/bookshelf/Contact.js
- src/v2/connectors/repository/company-contacts.js
- test/v2/connectors/bookshelf/CompanyContact.js
- test/v2/connectors/repository/company-contacts.js
WATER-2721
Updates the companies/{id}/contacts response to include the name of the
role by joining the role table
> Feat: Includes role in company contacts response

- test/v2/modules/addresses/validator.js
Supports https://github.com/DEFRA/water-abstraction-import/pull/195
Not a necessary/urgent change. The purpose of adding this test is to prevent the issue from cropping up again in the future (regression?)
> Added a test to support water-2815

- migrations/20201020083236-document-date-deleted.js
- migrations/sqls/20201020083236-document-date-deleted-down.sql
- migrations/sqls/20201020083236-document-date-deleted-up.sql
- src/controllers/contacts.js
- src/controllers/document-headers.js
- src/controllers/documents.js
- src/controllers/verification-documents.js
- src/v2/connectors/repository/documents.js
- src/v2/connectors/repository/queries/documents.js
- test/v2/connectors/repository/documents.js
WATER-2882
Changes the documents tables to allow a date_deleted to be set which
will cause the soft delete of the document.
This is to facilitate an update to the licence import to allow
documents that have been deleted in NALD to be hidden from the search
results.
> Fix: Allow soft deletion of documents

- src/v2/connectors/repository/addresses.js
- src/v2/connectors/repository/companies.js
- src/v2/connectors/repository/company-addresses.js
- src/v2/connectors/repository/helpers.js
- src/v2/lib/errors.js
- src/v2/lib/map-error-response.js
- src/v2/lib/pg-error.js
- src/v2/lib/wrap-service-call.js
- src/v2/modules/addresses/controller.js
- src/v2/modules/companies/controller.js
- src/v2/services/address.js
- src/v2/services/companies.js
- test/v2/connectors/repository/addresses.js
- test/v2/connectors/repository/companies.js
- test/v2/connectors/repository/company-addresses.js
- test/v2/modules/addresses/controller.js
- test/v2/modules/companies/controller.js
- test/v2/services/address.js
- test/v2/services/companies.js
* Responds with 409 code and existing entity if attempting to create company with same company number
* Implements a pattern where the UniqueConstraintValidation error is thrown and mapped 
* Modifies the 'create address' endpoint to use the same pattern
* Responds with 409 code and existing entity if attempting to create company address which conflicts with existing company ID / address ID / role ID combination
> Handles unique constraint violation when inserting company

- package.json
- src/v2/connectors/bookshelf/Company.js
- src/v2/connectors/repository/invoice-accounts.js
- test/v2/connectors/repository/invoice-accounts.js
WATER 3644
Theres are multiple names associated with companies this work will introduce a new flow to determine what name to show (just an if else in the UI )
```
if invoice.faoContact 
elif invoice.billingContact.agentCompanyName 
elif invoice.billingContact.roleContact.licenceHolder
elif invoice.billingContact.roleContact.billing
else invoice.name
```
> fix: billing contact account name

- .env.example
- config.js
- src/controllers/acceptance-tests.js
- src/routes/acceptance-tests.js
- src/v2/modules/test-data/routes.js
https://github.com/DEFRA/water-abstraction-team/issues/43
We are currently using `NODE_ENV` incorrectly; we set it to be the name of the specific environment (eg. `local`, `qa` etc.) when it should be more like the _type_ of environment (e.g. is it a dev environment, a production environment, etc.)
This means that tools like pm2 aren't correctly picking up that we are running in a dev-like or prod-like environment and configuring accordingly.
We, therefore, change how we use `NODE_ENV` to be the type of environment, with a separate `ENVIRONMENT` env var to set the actual environment (eg. `tst`, `pre` etc.)
> Correctly set NODE_ENV

- src/modules/health/controller.js
- src/modules/health/routes.js
- src/routes/crm.js
- test/modules/health/controller.test.js
https://github.com/DEFRA/water-abstraction-system/pull/8
We create a new endpoint `/health/info` which will be used by our System repo to display info. Currently this will be this repo's version and current git commit hash.
> Create `/health/info` endpoint

- config.js
- index.js
- src/controllers/contacts.js
- src/controllers/documents.js
- src/controllers/verification-documents.js
- src/controllers/verifications-by-document.js
- src/lib/CRM.js
- src/v2/modules/contacts/controller.js
- src/v2/modules/invoice-accounts/controller.js
- src/v2/modules/roles/controller.js
- test/controllers/contacts.test.js
- test/controllers/documents.test.js
https://github.com/DEFRA/water-abstraction-team/issues/45
Here we are trying to make the error logs more usable. Currently when an error happens the logs are getting jammed up with thousands of lines making them difficult to read and unusable. This change stops that pollution making them more usable.
> Stop passing err to logger.error

- package-lock.json
- package.json
- src/v2/connectors/repository/queries/companies.js
Dependabot cannot automatically bump the `standard` package as the update causes new linting issues.
This PR updates the `standard` package from v17.0.0 to v17.1.0 & fixes the linting issues this update creates.
> Update `standard` package

- migrations/20231221153217-alter-crm-v2-documents.js
- migrations/sqls/20231221153217-alter-crm-v2-documents-down.sql
- migrations/sqls/20231221153217-alter-crm-v2-documents-up.sql
https://eaflood.atlassian.net/browse/WATER-4292
As part of making the migrations work in `water-abstraction-system` we have been creating DB Views of the legacy crm data that better represent the data as we use it in our new service. Part of this exercise is pruning out the unused columns that exist in the legacy tables that are not utilised.
However, we have found that for some of the columns in the legacy data, whilst pointless, still need to be populated as they are set to `Not Nullable` in the legacy database tables. Therefore, we will set a default value for these columns in the legacy DB so that they are always populated even when they do not exist in our new Views.
The table columns that will be affected by this PR are:
- `crm_v2.documents.regime` - this is always "water" so it …
> Add defaults to unused columns in crm_v2.documents

- migrations/20240104130338-fix-missing-invoice-account-addresses.js
- migrations/sqls/20240104130338-fix-missing-invoice-account-addresses-down.sql
- migrations/sqls/20240104130338-fix-missing-invoice-account-addresses-up.sql
https://eaflood.atlassian.net/browse/WATER-4223
We are replacing the legacy bill run view with one we have developed in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system). During testing, it was found that there are examples of bill runs where a bill is missing from the view. When we checked the legacy version the bill was present so this was an issue just in our version of the page.
When we looked into the reason why, we found it was because the bill (`water.billing_invoice`) was linked to a billing account (`crm_v2.invoice_account`) that has no account address record (`crm_v2.invoice_account_address`). Since starting with the service we have been working under the assumption this should _never_ be the case; each billing account should have at least **one** …
> Fix missing invoice account address records

- migrations/20240107235932-alter-crm-document-header.js
- migrations/sqls/20240107235932-alter-crm-document-header-down.sql
- migrations/sqls/20240107235932-alter-crm-document-header-up.sql
https://eaflood.atlassian.net/browse/WATER-4292
As part of making the migrations work in `water-abstraction-system` we have been creating DB Views of the legacy crm data that better represent the data as we use it in our new service. Part of this exercise is pruning out the unused columns that exist in the legacy tables that are not utilised.
However, we have found that some of the columns in the legacy data, whilst pointless, still need to be populated as they are set to `Not Nullable` in the legacy database tables. Therefore, we will set a default value for these columns in the legacy DB so that they are always populated even when they do not exist in our new Views.
The table columns that will be affected by this PR are:
- `crm.document_header.system_id` - this is always "permit-repo" …
> Add defaults to unused column crm.document_header

- src/v2/connectors/repository/invoice-accounts.js
- src/v2/connectors/repository/queries/invoice-accounts.js
- src/v2/modules/invoice-accounts/controller.js
- src/v2/modules/invoice-accounts/routes.js
- src/v2/services/invoice-accounts.js
- test/v2/connectors/repository/invoice-accounts.test.js
- test/v2/modules/invoice-accounts/controller.test.js
- test/v2/services/invoice-accounts.test.js
https://eaflood.atlassian.net/browse/WATER-4437
The [water-abstraction-service](https://github.com/DEFRA/water-abstraction-service) had a scheduled job [Licence not in charge version workflow](https://github.com/DEFRA/water-abstraction-team/blob/main/jobs/service.md#licence-not-in-charge-version-workflow). It's intent was to add a `water.charge_version_workflow` record any time it saw a new or updated licence.
Our understanding is this was intended to keep the licence from being included in a bill run until Billing & Data has had a chance to review its charge versions.
However, it appeared to have stopped working. When we dug in we realised it seemed BullMQ jobs that were scheduled using cron syntax were not always getting their repeated jobs repeated! That was resolved with [New job to …
> Remove /invoice-accounts/recently-updated endpoint

- migrations/20240816131334-fix-deleted-document-headers.js
- migrations/sqls/20240816131334-fix-deleted-document-headers-down.sql
- migrations/sqls/20240816131334-fix-deleted-document-headers-up.sql
https://eaflood.atlassian.net/browse/WATER-4627
We received a report that an external user was unable to link **MD/054/0009/047** to their account (it returned the error "We cannot find these licence numbers"). We reproduced the issue in pre-prod and tracked down the cause.
When you add a licence number, the legacy code runs this query to pull it from `CRM.document_headers`.
```sql
SELECT
"crm"."document_header" .*
FROM
"crm"."document_header"
WHERE
"crm"."document_header"."system_external_id" = $1
AND "crm"."document_header"."company_entity_id" IS NULL
AND "crm"."document_header"."metadata"->'IsCurrent' != $2
AND "crm"."document_header"."date_deleted" IS NULL
AND "crm"."document_header"."metadata"->>'IsCurrent' != $3
ORDER BY
"crm"."document_header"."system_external_id" ASC
LIMIT $4
-- [ …
```
> Data fix for wrongly deleted document headers

- migrations/20241003162404-fix-multiple-current-licence-holders.js
- migrations/sqls/20241003162404-fix-multiple-current-licence-holders-down.sql
- migrations/sqls/20241003162404-fix-multiple-current-licence-holders-up.sql
https://eaflood.atlassian.net/browse/WATER-4696
Specifically, `7/34/11/*G/0462` needs the fix. Users reported an issue with licence holder information.
- Two licence holders were listed on the view licence contact details page (there should only be one)
- When adding a new charge version, the journey was suggesting to create the new billing account using the old company details
We found the issue was that for this licence, we have two entries in `crm_v2.document_roles` with the role of `licenceHolder` and no end dates. In the case of the licence holder, the service derives the 'current' licence holder by selecting the one with no end date (there should only be one).
Because we have 2 with no end date, view contact details shows both. In the legacy charge version journey, it gets all …
> Data fix for multiple 'current' licence holders

- migrations/20241014133216-alter-crm-v2-documents-defaults.js
- migrations/sqls/20241014133216-alter-crm-v2-documents-defaults.js-down.sql
- migrations/sqls/20241014133216-alter-crm-v2-documents-defaults.js-up.sql
https://eaflood.atlassian.net/browse/WATER-4708
As part of the ongoing work to move the import code into WRLS. We need to use constraints to enforce data consistency and uniqueness.
Previously the document type and regime where defaulted and used to form a unique key. We no longer need to do this.
This chance simplifies the unique constraint to just the document ref (licence ref).
> Alter CRM document unique constraints

- migrations/20250702193402-fix-deleted-registered-licences.js
- migrations/sqls/20250702193402-fix-deleted-registered-licences-down.sql
- migrations/sqls/20250702193402-fix-deleted-registered-licences-up.sql
https://eaflood.atlassian.net/browse/WATER-5038
We've updated the overnight import from NALD to include a clean-up step.
Now, records that exist in WRLS but don't exist in NALD will be deleted. That is, unless they are linked to something.
The following seven licences have been registered to user accounts but have since been deleted from NALD.
- 03/28/81/0045/1/RO1
- 6/33/48/*S/0234/L
- 7/34/06/*G/0279A/L
- AN/034/0006/017/L
- AN/034/0006/024/L
- AN/034/0009/004/L
- TH/039/0022/029/L
You should be able to unlink them through the UI, but that does not seem to be working in this case, likely due to the legacy code not being compatible with the deletion of unrelated records.
If the unlink was working, all it does is set `company_entity_id` to null in the `crm.document_header` table for the …
> Data fix to unlink users from deleted licences
