DEFRA/water-abstraction-tactical-crm

src/lib/CRM.js

NOTE: Query now only returns document that the user specified in entity_id param

Modify roles query.

---

src/lib/CRM.js

Recently removed the `is_primary` field so queries should no longer
cater for it.

Feat: Updates queries now isPrimary has gone.

---

src/controllers/contacts.js
src/controllers/document-headers.js
src/controllers/verification-documents.js
src/lib/CRM.js
src/routes/crm.js

Delete the verifications and any verification documents.

Feature: Adds a resource to delete verifications

---

migrations/20180809163444-lowercase-individuals-emails.js
migrations/sqls/20180809163444-lowercase-individuals-emails-down.sql
migrations/sqls/20180809163444-lowercase-individuals-emails-up.sql
src/controllers/entities.js
src/lib/CRM.js
test/controllers/entities.js

WATER-1295
- Updates all individual entity names to lowercase via migration
- Updates entities controller to Lower case entity name for individuals on create

Feature: Handle entity name casing

---

.labrc.js
.travis.yml
package.json
src/controllers/contacts.js

Changes the test tasks to cater for local dev and execution on Travis.
Locally only the lab tests are run. Therefore the code coverage is not
to provide a cleaner output whilst developing.
Travis then has a separate task which includes the code coverage.

Feat: Separate test tasks

---

.labrc.js
package-lock.json
package.json

WATER-1557
Updates to a version that does not have a recursive function that can be called in a way that never returns.

Fix: Update airbrake js

---

index.js
src/controllers/contacts.js
src/controllers/document-headers.js
src/controllers/verification-documents.js
src/controllers/verifications-by-document.js
src/lib/CRM.js
src/lib/connectors/db.js
src/lib/logger/index.js

Changes console.log to use the Winston logger directly, or where
possible uses HAPI's `request.log` or `server.log`.
Some console.log statements were just removed, whereas some have been
replaced with the new loggers.
Also updates the logger itself to allow empty values for the Airbrake
host and key. In development we don't want to send errors to Errbit.

Feature: Improve logging

---

.codeclimate.json
.env.example
.labrc.js
.travis.yml
README.MD
config.js
index.js
src/lib/logger/index.js

WATER-1685
- Remove unused cache key
- Use upper case env variable keys.
- Adds an example .env file to highlight required env vars.

Feat: Consolidate env variables

---

migrations/20181123165313-remove-erroneous-verification-id.js
migrations/sqls/20181123165313-remove-erroneous-verification-id-down.sql
migrations/sqls/20181123165313-remove-erroneous-verification-id-up.sql
package-lock.json
package.json

A records has a verification_id which is not expected. This deletes to
allow a user to claim the licence.
WATER-1736

Fix: Corrects a document_header record

---

src/controllers/contacts.js
src/controllers/verification-documents.js
src/controllers/verifications-by-document.js
src/lib/CRM.js

This gives better detail at Errbit

Feat: Use logger instead of request.log for errors

---

migrations/20181207111755-entity-add-date-created.js
migrations/20181207115121-document-header-drop-verified.js
migrations/sqls/20181207111755-entity-add-date-created-down.sql
migrations/sqls/20181207111755-entity-add-date-created-up.sql
migrations/sqls/20181207115121-document-header-drop-verified-down.sql
migrations/sqls/20181207115121-document-header-drop-verified-up.sql
package-lock.json
package.json
src/controllers/document-headers.js
src/controllers/entities.js
src/lib/CRM.js
test/controllers/entities.js
test/lib/CRM.js
test/verify.js

WATER-1753
- Adds timestamps to the entity table
- Removes the `verified` field from the `document_header` table

Fix: Check for verified documents by company id

---

package-lock.json
package.json

Also updates the name and description.

Chore: Adds the repository to the package.json

---

src/controllers/status.js
src/routes/crm.js
test/controllers/status.js

Feat: Adds the version to the status response

---

src/controllers/documents.js

- Return 404 when document does not exist
- Return 200 with empty array if document exists with no users

For document users call:

---

migrations/20191021152244-rename-ias-account-number.js
migrations/sqls/20191021152244-rename-ias-account-number-down.sql
migrations/sqls/20191021152244-rename-ias-account-number-up.sql
src/v2/connectors/repository/queries/document-roles.js
src/v2/modules/documents/lib/mappers.js
test/v2/modules/documents/lib/mappers.js

Feat: Renames iasAccountNumber to invoiceAccountNumber

---

index.js
package-lock.json
package.json
src/controllers/contacts.js
src/controllers/document-headers.js
src/controllers/verification-documents.js
src/controllers/verifications.js
src/lib/CRM.js
src/lib/sql.js
src/v2/modules/documents/routes.js
test/controllers/document-headers.js
test/controllers/entities.js
test/routes/documents.js
test/verify.js

Updates dependencies as suggested by dependabot including updates to
linter version which then required code updated to satisfy new rules.

Chore: Update dependencies

---

migrations/20191126172844-change-document-external-id.js
migrations/sqls/20191126172844-change-document-external-id-down.sql
migrations/sqls/20191126172844-change-document-external-id-up.sql
package-lock.json
package.json

WATER-2388
Updates all the crm_v2.documents.externalId values to remove the final
segement that represented the increment number

Fix: Updates all documents.externalId values

---

migrations/20191203111359-document-header-index.js
migrations/sqls/20191203111359-document-header-index-down.sql
migrations/sqls/20191203111359-document-header-index-up.sql

Adds indexes to the table that are queried when the select company page
is presented to an external user.

Fix: Improves the query time for select company queries

---

src/lib/connectors/db.js
test/lib/connectors/db.js

Currently date fields are output as a timestamp

Modify pg to returns date fields in format YYYY-MM-DD

---

src/v2/connectors/repository/InvoiceAccountsRepository.js
src/v2/connectors/repository/index.js
src/v2/connectors/repository/queries/invoice-accounts.js
src/v2/modules/invoice-accounts/controller.js
src/v2/modules/invoice-accounts/routes.js
src/v2/routes.js
test/v2/connectors/repository/InvoiceAccountRepository.js
test/v2/modules/invoice-accounts/controller.js

WATER-2414
Adds resource at '/crm/2.0/invoice-accounts' to get invoice account
objects including company data

Feat: Add resource to get invoice accounts

---

package-lock.json
package.json
src/v2/connectors/repository/InvoiceAccountsRepository.js
src/v2/connectors/repository/queries/invoice-accounts.js
src/v2/modules/invoice-accounts/controller.js
src/v2/modules/invoice-accounts/routes.js
test/v2/connectors/repository/InvoiceAccountRepository.js
test/v2/modules/invoice-accounts/controller.js

Feat: Get a single invoice account by id

---

package-lock.json
package.json
src/v2/connectors/repository/addresses.js
src/v2/connectors/repository/companies.js
src/v2/connectors/repository/helpers.js
src/v2/lib/errors.js
src/v2/lib/map-error-response.js
src/v2/modules/addresses/controller.js
src/v2/modules/addresses/routes.js
src/v2/modules/addresses/validator.js
src/v2/routes.js
src/v2/services/address.js
test/v2/connectors/repository/addresses.js
test/v2/connectors/repository/helpers.js
test/v2/lib/map-error-response.js
test/v2/modules/addresses/controller.js
test/v2/modules/addresses/routes.js
test/v2/modules/addresses/validator.js
test/v2/services/address.js

Feat: Allow an address to be added to the CRM

---

src/v2/connectors/bookshelf/CompanyContact.js
src/v2/connectors/bookshelf/index.js
src/v2/connectors/repository/company-contacts.js
src/v2/connectors/repository/index.js
src/v2/lib/errors.js
src/v2/lib/map-error-response.js
src/v2/lib/validators.js
src/v2/modules/companies/controller.js
src/v2/modules/companies/routes.js
src/v2/services/companies.js
test/v2/connectors/bookshelf/CompanyContact.js
test/v2/connectors/repository/company-contacts.js
test/v2/modules/companies/controller.js
test/v2/modules/companies/routes.js
test/v2/services/companies.js

Feat/water 2635 add company contact

End point to add a contact to a company

---

package-lock.json
package.json
src/v2/connectors/repository/addresses.js
src/v2/connectors/repository/companies.js
src/v2/connectors/repository/company-addresses.js
src/v2/connectors/repository/company-contacts.js
src/v2/connectors/repository/contacts.js
src/v2/connectors/repository/document-roles.js
src/v2/connectors/repository/documents.js
src/v2/connectors/repository/helpers.js
src/v2/connectors/repository/invoice-account-addresses.js
src/v2/connectors/repository/invoice-accounts.js
src/v2/modules/test-data/controller.js
src/v2/modules/test-data/routes.js
src/v2/routes.js
src/v2/services/test-data.js
test/v2/connectors/repository/addresses.js
test/v2/connectors/repository/companies.js
test/v2/connectors/repository/company-addresses.js
test/v2/connectors/repository/company-contacts.js
test/v2/connectors/repository/contacts.js
test/v2/connectors/repository/document-roles.js
test/v2/connectors/repository/documents.js
test/v2/connectors/repository/helpers.js
test/v2/connectors/repository/invoice-account-addresses.js
test/v2/connectors/repository/invoice-accounts.js
test/v2/modules/test-data/controller.js
test/v2/modules/test-data/routes.js
test/v2/services/test-data.js

WATER-2640
Adds a new resource available outside of live to delete all the test
data that may have been created.

Feat: Tear down the test data

---

src/v2/connectors/bookshelf/Company.js
src/v2/connectors/repository/company-addresses.js
src/v2/connectors/repository/company-contacts.js
src/v2/connectors/repository/invoice-accounts.js
src/v2/connectors/repository/queries/invoice-accounts.js
src/v2/lib/errors.js
src/v2/lib/map-error-response.js
src/v2/lib/validators.js
src/v2/lib/wrap-service-call.js
src/v2/modules/companies/controller.js
src/v2/modules/companies/routes.js
src/v2/modules/invoice-accounts/routes.js
src/v2/services/companies.js
src/v2/services/invoice-accounts.js
test/v2/connectors/repository/company-addresses.js
test/v2/connectors/repository/company-contacts.js
test/v2/connectors/repository/invoice-accounts.js
test/v2/modules/companies/controller.js
test/v2/modules/invoice-accounts/routes.js
test/v2/services/companies.js
test/v2/services/invoice-accounts.js

Adds:
- Get addresses for a company
- Get contacts for a company
- Supply a region code when adding an invoice account to have the account number auto-generated
A data envelope { data : [] } has not been used for arrays as other methods in the v2 folder did not seem to be using one.

Adds APIs for invoice accounts flow

---

src/controllers/contacts.js
test/controllers/contacts.js

Fix: Return an error response from getContacts

---

src/v2/modules/contacts/routes.js
src/v2/modules/roles/controller.js
src/v2/modules/roles/routes.js
src/v2/routes.js
src/v2/services/roles.js
test/v2/modules/contacts/routes.js
test/v2/modules/roles/controller.js
test/v2/modules/roles/routes.js
test/v2/services/roles.js

WATER-2744
Exposes a new resource to get a role entity by role name.

Feat: Adds resource to get role by name

---

src/lib/CRM.js

Accidentally introduced in a previous PR I think.
Fixes this issue: https://eaflood.atlassian.net/browse/WATER-2919

Removes unwanted semi colon

---

src/lib/CRM.js

WATER-2430
Removes any extra args passed to Boom.unauthorized where they do not
adhere to the signature of the function.

Fix: Updates the use of Boom.unauthorized

---

.github/workflows/ci.yml
migrations/20210429104232-entity-hash-columns.js
migrations/sqls/20210429104232-entity-hash-columns-down.sql
migrations/sqls/20210429104232-entity-hash-columns-up.sql
package.json
src/v2/connectors/repository/invoice-accounts.js
src/v2/connectors/repository/queries/invoice-accounts.js
src/v2/modules/invoice-accounts/controller.js
src/v2/modules/invoice-accounts/routes.js
src/v2/services/invoice-accounts.js
test/v2/connectors/repository/invoice-accounts.js
test/v2/modules/invoice-accounts/controller.js
test/v2/services/invoice-accounts.js

This set of pull requests enables the service to inform the charge module when there has been an entity change in the NALD data which is relevant to an invoice account.
Service pull request: https://github.com/DEFRA/water-abstraction-service/pull/1374
CRM pull request: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/780
Import pull request: https://github.com/DEFRA/water-abstraction-import/pull/299
Original ticket: https://eaflood.atlassian.net/browse/WATER-3081

Feat/water 3081 informing CM when there has been a NALD linked entities change

---

src/v2/modules/contacts/routes.js

See https://eaflood.atlassian.net/browse/WATER-3193
Please note this allows the salutation (or title) to be updated.

WATER-3193:Edit contact name including salutation

---

src/controllers/document-headers.js

Original ticket: https://eaflood.atlassian.net/browse/WATER-3368
Service PR: https://github.com/DEFRA/water-abstraction-service/pull/1549
UI PR: https://github.com/DEFRA/water-abstraction-ui/pull/1965
CRM PR: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/871

Make expired licences searchable again

---

src/v2/modules/contacts/routes.js

See: https://eaflood.atlassian.net/browse/WATER-3193
Please note that this is a prerequisite for the following PRs:
https://github.com/DEFRA/water-abstraction-service/pull/1552
https://github.com/DEFRA/water-abstraction-ui/pull/1967

WATER-3193: Edit a contact and department separately

---

src/v2/lib/entity-handlers.js
test/v2/lib/entity-handlers.js

See: https://eaflood.atlassian.net/browse/WATER-3349
Please note this PR is a prerequisite for PRs:
- https://github.com/DEFRA/water-abstraction-service/pull/1564
- https://github.com/DEFRA/water-abstraction-ui/pull/1970

WATER-3349: Delete a company contact

---

migrations/20211116131609-fix-contacts.js
migrations/sqls/20211116131609-fix-contacts-down.sql
migrations/sqls/20211116131609-fix-contacts-up.sql
src/v2/modules/contacts/routes.js

See: https://eaflood.atlassian.net/browse/WATER-3379
Please note this PR is a prerequisite for the following PRs:
https://github.com/DEFRA/water-abstraction-service/pull/1570
https://github.com/DEFRA/water-abstraction-ui/pull/1975

WATER-3379: Update a contact, add a new charge version it throws error

---

src/v2/modules/invoice-accounts/controller.js

https://eaflood.atlassian.net/browse/WATER-3399

Return 202 instead of waiting for data processing outcome

---

.labrc.js
src/v2/connectors/repository/companies.js
src/v2/connectors/repository/queries/companies.js
src/v2/connectors/repository/queries/documents.js
src/v2/modules/companies/controller.js
src/v2/modules/companies/routes.js
src/v2/services/companies.js
test/v2/connectors/repository/companies.js
test/v2/modules/companies/controller.js
test/v2/services/companies.js

UI: https://github.com/DEFRA/water-abstraction-ui/pull/2054
CRM: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/879
Service: https://github.com/DEFRA/water-abstraction-service/pull/1642
Originating tickets: 
- https://eaflood.atlassian.net/browse/WATER-3383
- https://eaflood.atlassian.net/browse/WATER-3540

Adds WAA Email Contact fetching endpoint to CRMv2

---

package.json

Addresses: https://github.com/DEFRA/water-abstraction-team/issues/11

chore: remove nodemon

---

migrations/20221018092848-remove-problem-licences.js
migrations/sqls/20221018092848-remove-problem-licences-down.sql
migrations/sqls/20221018092848-remove-problem-licences-up.sql

https://eaflood.atlassian.net/jira/software/c/projects/WATER/boards/96?modal=detail&selectedIssue=WATER-3710 https://eaflood.atlassian.net/jira/software/c/projects/WATER/boards/96?modal=detail&selectedIssue=WATER-3756
We have two licences that hold problematic data currently in the water schema in the database. Here we are creating a migration script for both to remove these records.

Fix problem licence data

---

migrations/20250109115438-alter-document-header-add-index.js
migrations/sqls/20250109115438-alter-document-header-add-index-down.sql
migrations/sqls/20250109115438-alter-document-header-add-index-up.sql

https://eaflood.atlassian.net/browse/WATER-4868
https://eaflood.atlassian.net/browse/WATER-4839
As part of the the ongoing work to replace the legacy notifications we have established an efficient query to replace most of the legacy batch notification code.
This query did take about 12 seconds to complete we deemed this too slow for out needs so the unique indexing of the `system_external_id` has been added to not only ensure the `system_external_id` unique but to increase query efficiency. THe query now takes around 600ms.
This query will be added to the system repo in a separate piece of work.

Add index to system_external_id
